baseURL: "/"
languageCode: "ja-jp"
defaultContentLanguage: "ja"
title: "www.λ沢.net"
theme: "terminal"
googleAnalytics: ""
paginate: 10

params:
  contentTypeName: posts
  themeColor: orange
  showMenuItems: 10
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  favicon: "favicon.ico"
  oneHeadingSize: false

languages:
  ja:
    languageName: Japanese
    title: λ沢.net
    subtitle: ""
    keywords: ""
    menuMore: もっと見る
    readMore: もっと読む
    readOtherPosts: 他の投稿を読む

    params:
      logo:
        logoText: λ沢.net
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: About
          url: /about
          weight: 1
        - identifier: GitHub
          name: GitHub
          url: https://github.com/lambdasawa
          weight: 2
        - identifier: Twitter
          name: Twitter
          url: https://twitter.com/lambdasawa
          weight: 3
        - identifier: discord
          name: Discord
          url: https://discordapp.com/users/253206897950195722
          weight: 4
        - identifier: mail
          name: Mail
          url: mailto:lambdasawa@gmail.com
          weight: 5
        - identifier: feed
          name: Feed
          url: /index.xml
          weight: 6

deployment:
  targets:
    URL: "s3://www.lambdasawa.net?region=ap-northeast-1"
    cloudFrontDistributionID: ""
  matchers:
    - pattern: "^.+\\.(js|css|svg|ttf)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
    - pattern: "^.+\\.(html|xml|json)$"
      gzip: true
