baseURL: "/"
languageCode: "ja-jp"
defaultContentLanguage: "ja"
title: "www.λ沢.net"
theme: "terminal"
googleAnalytics: ""
paginate: 10

params:
  contentTypeName: posts
  themeColor: orange
  showMenuItems: 3
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  favicon: "favicon.ico"
  oneHeadingSize: false

languages:
  ja:
    languageName: Japanese
    title: λ沢.net
    subtitle: ""
    keywords: ""
    menuMore: もっと見る
    readMore: もっと読む
    readOtherPosts: 他の投稿を読む

    params:
      logo:
        logoText: λ沢.net
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: About
          url: /about

deployment:
  targets:
    URL: "s3://www.lambdasawa.net?region=ap-northeast-1"
    cloudFrontDistributionID: ""
  matchers:
    - pattern: "^.+\\.(js|css|svg|ttf)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
    - pattern: "^.+\\.(html|xml|json)$"
      gzip: true
