name: deploy to amazon s3

on:
  push:
    branches:
      - master
      - ci

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout with submodule
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.62.2"

      - name: Build
        run: hugo --minify

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Deploy
        run: |
          yarn cdk deploy
