name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: ${{ secrets.SLACK_CHANNEL }}
        if: always()

      - name: Checkout with submodule
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.79.1"
          extended: true

      - name: Build
        run: hugo --minify
        env:
          HUGO_googleAnalytics: ${{ secrets.HUGO_googleAnalytics }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Deploy
        run: |
          set -xe
          cd infra
          npm i
          npm run cdk -- deploy --require-approval never --events logs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          ROUTE53_HOSTED_ZONE: ${{ secrets.ROUTE53_HOSTED_ZONE }}
          ROUTE53_DOMAIN: ${{ secrets.ROUTE53_DOMAIN }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_LOCAL_ASSET_PATH: ${{ secrets.S3_LOCAL_ASSET_PATH }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ secrets.SLACK_CHANNEL }}
        if: always()
